package Isis;


/**
* Isis/Attrib.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IsisCommon.idl
* Tuesday, December 6, 2016 9:17:28 PM IST
*/

public final class Attrib implements org.omg.CORBA.portable.IDLEntity
{
  public String attributeName = null;

  // Attribute Name
  public String attributeValue = null;

  public Attrib ()
  {
  } // ctor

  public Attrib (String _attributeName, String _attributeValue)
  {
    attributeName = _attributeName;
    attributeValue = _attributeValue;
  } // ctor

} // class Attrib
