package Isis;

/**
* Isis/AttribHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IsisCommon.idl
* Tuesday, December 6, 2016 9:17:28 PM IST
*/

public final class AttribHolder implements org.omg.CORBA.portable.Streamable
{
  public Isis.Attrib value = null;

  public AttribHolder ()
  {
  }

  public AttribHolder (Isis.Attrib initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Isis.AttribHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Isis.AttribHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Isis.AttribHelper.type ();
  }

}
