package Isis;


/**
* Isis/ErrorGroup.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IsisCommon.idl
* Tuesday, December 6, 2016 9:17:28 PM IST
*/


// Error groups
public class ErrorGroup implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 5;
  private static Isis.ErrorGroup[] __array = new Isis.ErrorGroup [__size];

  public static final int _APPLICATION_ERROR = 0;
  public static final Isis.ErrorGroup APPLICATION_ERROR = new Isis.ErrorGroup(_APPLICATION_ERROR);
  public static final int _DATABASE_ERROR = 1;
  public static final Isis.ErrorGroup DATABASE_ERROR = new Isis.ErrorGroup(_DATABASE_ERROR);
  public static final int _NO_DATA_ERROR = 2;
  public static final Isis.ErrorGroup NO_DATA_ERROR = new Isis.ErrorGroup(_NO_DATA_ERROR);
  public static final int _SYSTEM_ERROR = 3;
  public static final Isis.ErrorGroup SYSTEM_ERROR = new Isis.ErrorGroup(_SYSTEM_ERROR);
  public static final int _COMMUNICATIONS_ERROR = 4;
  public static final Isis.ErrorGroup COMMUNICATIONS_ERROR = new Isis.ErrorGroup(_COMMUNICATIONS_ERROR);

  public int value ()
  {
    return __value;
  }

  public static Isis.ErrorGroup from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected ErrorGroup (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class ErrorGroup
