package Isis;


/**
* Isis/ErrorGroupHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IsisCommon.idl
* Tuesday, December 6, 2016 9:17:28 PM IST
*/


// Error groups
abstract public class ErrorGroupHelper
{
  private static String  _id = "IDL:Isis/ErrorGroup:1.0";

  public static void insert (org.omg.CORBA.Any a, Isis.ErrorGroup that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Isis.ErrorGroup extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_enum_tc (Isis.ErrorGroupHelper.id (), "ErrorGroup", new String[] { "APPLICATION_ERROR", "DATABASE_ERROR", "NO_DATA_ERROR", "SYSTEM_ERROR", "COMMUNICATIONS_ERROR"} );
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Isis.ErrorGroup read (org.omg.CORBA.portable.InputStream istream)
  {
    return Isis.ErrorGroup.from_int (istream.read_long ());
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Isis.ErrorGroup value)
  {
    ostream.write_long (value.value ());
  }

}
