package Isis;


/**
* Isis/InterfaceError.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IsisCommon.idl
* Tuesday, December 6, 2016 9:17:28 PM IST
*/


// Interface exception
public final class InterfaceError extends org.omg.CORBA.UserException
{
  public Isis.ErrorGroup errorGroup = null;

  // Error group
  public String errorCode = null;

  // Error code
  public String errorMsg = null;

  public InterfaceError ()
  {
    super(InterfaceErrorHelper.id());
  } // ctor

  public InterfaceError (Isis.ErrorGroup _errorGroup, String _errorCode, String _errorMsg)
  {
    super(InterfaceErrorHelper.id());
    errorGroup = _errorGroup;
    errorCode = _errorCode;
    errorMsg = _errorMsg;
  } // ctor


  public InterfaceError (String $reason, Isis.ErrorGroup _errorGroup, String _errorCode, String _errorMsg)
  {
    super(InterfaceErrorHelper.id() + "  " + $reason);
    errorGroup = _errorGroup;
    errorCode = _errorCode;
    errorMsg = _errorMsg;
  } // ctor

} // class InterfaceError
