package Isis;


/**
* Isis/oct_16_seqHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IsisCommon.idl
* Tuesday, December 6, 2016 9:17:28 PM IST
*/


// Transaction Id
public final class oct_16_seqHolder implements org.omg.CORBA.portable.Streamable
{
  public byte value[] = null;

  public oct_16_seqHolder ()
  {
  }

  public oct_16_seqHolder (byte[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Isis.oct_16_seqHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Isis.oct_16_seqHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Isis.oct_16_seqHelper.type ();
  }

}
