package Isis;

/**
* Isis/TransactionInfoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IsisCommon.idl
* Tuesday, December 6, 2016 9:17:28 PM IST
*/

public final class TransactionInfoHolder implements org.omg.CORBA.portable.Streamable
{
  public Isis.TransactionInfo value = null;

  public TransactionInfoHolder ()
  {
  }

  public TransactionInfoHolder (Isis.TransactionInfo initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Isis.TransactionInfoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Isis.TransactionInfoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Isis.TransactionInfoHelper.type ();
  }

}
