package Isis;


/**
* Isis/TransactionInfoHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IsisCommon.idl
* Tuesday, December 6, 2016 9:17:28 PM IST
*/

abstract public class TransactionInfoHelper
{
  private static String  _id = "IDL:Isis/TransactionInfo:1.0";

  public static void insert (org.omg.CORBA.Any a, Isis.TransactionInfo that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Isis.TransactionInfo extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [4];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (2);
          _members0[0] = new org.omg.CORBA.StructMember (
            "originId",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[1] = new org.omg.CORBA.StructMember (
            "userId",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_octet);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (16, _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (Isis.oct_16_seqHelper.id (), "oct_16_seq", _tcOf_members0);
          _members0[2] = new org.omg.CORBA.StructMember (
            "txId",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (16);
          _members0[3] = new org.omg.CORBA.StructMember (
            "externalUserId",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (Isis.TransactionInfoHelper.id (), "TransactionInfo", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Isis.TransactionInfo read (org.omg.CORBA.portable.InputStream istream)
  {
    Isis.TransactionInfo value = new Isis.TransactionInfo ();
    value.originId = istream.read_string ();
    if (value.originId.length () > (2))
      throw new org.omg.CORBA.MARSHAL (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    value.userId = istream.read_long ();
    value.txId = Isis.oct_16_seqHelper.read (istream);
    value.externalUserId = istream.read_string ();
    if (value.externalUserId.length () > (16))
      throw new org.omg.CORBA.MARSHAL (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Isis.TransactionInfo value)
  {
    if (value.originId.length () > (2))      throw new org.omg.CORBA.MARSHAL (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    ostream.write_string (value.originId);
    ostream.write_long (value.userId);
    Isis.oct_16_seqHelper.write (ostream, value.txId);
    if (value.externalUserId.length () > (16))      throw new org.omg.CORBA.MARSHAL (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    ostream.write_string (value.externalUserId);
  }

}
