package Isis;


/**
* Isis/TransactionInfo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IsisCommon.idl
* Tuesday, December 6, 2016 9:17:28 PM IST
*/

public final class TransactionInfo implements org.omg.CORBA.portable.IDLEntity
{
  public String originId = null;

  // Origin Id
  public int userId = (int)0;

  // User Id
  public byte txId[] = null;

  // Transaction Id
  public String externalUserId = null;

  public TransactionInfo ()
  {
  } // ctor

  public TransactionInfo (String _originId, int _userId, byte[] _txId, String _externalUserId)
  {
    originId = _originId;
    userId = _userId;
    txId = _txId;
    externalUserId = _externalUserId;
  } // ctor

} // class TransactionInfo
