package HighSpeed;


/**
* HighSpeed/ActionAttributeListHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HighSpeedExt.idl
* Tuesday, December 6, 2016 9:17:28 PM IST
*/


// Action attribute list
abstract public class ActionAttributeListHelper
{
  private static String  _id = "IDL:HighSpeed/ActionAttributeList:1.0";

  public static void insert (org.omg.CORBA.Any a, HighSpeed.ActionAttribute[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static HighSpeed.ActionAttribute[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = HighSpeed.ActionAttributeHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (HighSpeed.ActionAttributeListHelper.id (), "ActionAttributeList", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static HighSpeed.ActionAttribute[] read (org.omg.CORBA.portable.InputStream istream)
  {
    HighSpeed.ActionAttribute value[] = null;
    int _len0 = istream.read_long ();
    value = new HighSpeed.ActionAttribute[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = HighSpeed.ActionAttributeHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, HighSpeed.ActionAttribute[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      HighSpeed.ActionAttributeHelper.write (ostream, value[_i0]);
  }

}
