package HighSpeed;


/**
* HighSpeed/ActionAttribute.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HighSpeedExt.idl
* Tuesday, December 6, 2016 9:17:28 PM IST
*/

public final class ActionAttribute implements org.omg.CORBA.portable.IDLEntity
{
  public String satId = null;

  // Service Attribute Id
  public String currentSacId = null;

  // Current Service Action Id
  public String newSacId = null;

  // New Service Action Id
  public String dateFrom = null;

  // Date From
  public String dateTo = null;

  public ActionAttribute ()
  {
  } // ctor

  public ActionAttribute (String _satId, String _currentSacId, String _newSacId, String _dateFrom, String _dateTo)
  {
    satId = _satId;
    currentSacId = _currentSacId;
    newSacId = _newSacId;
    dateFrom = _dateFrom;
    dateTo = _dateTo;
  } // ctor

} // class ActionAttribute
