package HighSpeed;


/**
* HighSpeed/Lookup.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HighSpeedExt.idl
* Tuesday, December 6, 2016 9:17:28 PM IST
*/

public final class Lookup implements org.omg.CORBA.portable.IDLEntity
{

  //--------------------------|-------------
  public String actionType = null;

  // ActionType | ActionType
  public String elementTwo = null;

  // SubscriberID | Listboxname
  public String elementThree = null;

  // SubscriberID Type | DisplayValue
  public String elementFour = null;

  // Listboxidentifier | ParValue
  public String elementFive = null;

  // Service provider Code | null
  public String elementSix = null;

  // Package Identifier  | Data Type
  public String elementSeven = null;

  public Lookup ()
  {
  } // ctor

  public Lookup (String _actionType, String _elementTwo, String _elementThree, String _elementFour, String _elementFive, String _elementSix, String _elementSeven)
  {
    actionType = _actionType;
    elementTwo = _elementTwo;
    elementThree = _elementThree;
    elementFour = _elementFour;
    elementFive = _elementFive;
    elementSix = _elementSix;
    elementSeven = _elementSeven;
  } // ctor

} // class Lookup
