package HighSpeed;


/**
* HighSpeed/LookupListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HighSpeedExt.idl
* Tuesday, December 6, 2016 9:17:28 PM IST
*/


// List of Lookup structure
public final class LookupListHolder implements org.omg.CORBA.portable.Streamable
{
  public HighSpeed.Lookup value[] = null;

  public LookupListHolder ()
  {
  }

  public LookupListHolder (HighSpeed.Lookup[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = HighSpeed.LookupListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    HighSpeed.LookupListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return HighSpeed.LookupListHelper.type ();
  }

}
