package HighSpeed;


/**
* HighSpeed/ManagerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HighSpeedExt.idl
* Tuesday, December 6, 2016 9:17:28 PM IST
*/


//--------------------------------------------------------------------------
public interface ManagerOperations 
{

  //----------------------------------------------------------------------
  void PerformLogOn (String originId, String userName, String passWord, org.omg.CORBA.IntHolder userId, org.omg.CORBA.StringHolder securityKey) throws Isis.InterfaceError;
  void PerformLogOff (String originId, int userId, String securityKey) throws Isis.InterfaceError;
  HighSpeed.TaskResult PerformFunction (String originId, int userId, String securityKey, String functionSelector, Isis.AttributeListHolder attributeList) throws Isis.InterfaceError;
  HighSpeed.TaskResult ExecFunction (String originId, int userId, String securityKey, String functionSelector, Isis.AttributeListHolder attributeList, HighSpeed.ServiceActionListHolder serviceActionList, HighSpeed.ActionAttributeListHolder actionAttributeList, HighSpeed.PartyHolder partyDetails, HighSpeed.RequestResultListHolder requestResultList) throws Isis.InterfaceError;
  HighSpeed.TaskResult QueryFunction (String originId, int userId, String securityKey, String functionSelector, Isis.AttributeListHolder attributeList, HighSpeed.ServiceActionListHolder serviceActionList, HighSpeed.ActionAttributeListHolder actionAttributeList, HighSpeed.SubAttributeListHolder subAttributeList, HighSpeed.PartyHolder partyDetails, HighSpeed.RequestResultListHolder requestResultList) throws Isis.InterfaceError;
  HighSpeed.TaskResult Lookup (String originId, int userId, String securityKey, String functionSelector, HighSpeed.LookupListHolder lookupList) throws Isis.InterfaceError;
  boolean ValidateSecurityKey (String originId, int userId, String securityKey) throws Isis.InterfaceError;
} // interface ManagerOperations
