package HighSpeed;


/**
* HighSpeed/ManagerHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HighSpeedExt.idl
* Tuesday, December 6, 2016 9:17:28 PM IST
*/


//--------------------------------------------------------------------------
abstract public class ManagerHelper
{
  private static String  _id = "IDL:HighSpeed/Manager:1.0";

  public static void insert (org.omg.CORBA.Any a, HighSpeed.Manager that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static HighSpeed.Manager extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (HighSpeed.ManagerHelper.id (), "Manager");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static HighSpeed.Manager read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ManagerStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, HighSpeed.Manager value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static HighSpeed.Manager narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof HighSpeed.Manager)
      return (HighSpeed.Manager)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      HighSpeed._ManagerStub stub = new HighSpeed._ManagerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static HighSpeed.Manager unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof HighSpeed.Manager)
      return (HighSpeed.Manager)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      HighSpeed._ManagerStub stub = new HighSpeed._ManagerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
