package HighSpeed;


/**
* HighSpeed/PartyContactNum.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HighSpeedExt.idl
* Tuesday, December 6, 2016 9:17:28 PM IST
*/

public final class PartyContactNum implements org.omg.CORBA.portable.IDLEntity
{
  public int seq = (int)0;

  // Unique ID
  public String countryCode = null;

  // Country dialling code
  public String areaNetCode = null;

  // Area network code
  public String dialNum = null;

  // Dialling number
  public String type = null;

  public PartyContactNum ()
  {
  } // ctor

  public PartyContactNum (int _seq, String _countryCode, String _areaNetCode, String _dialNum, String _type)
  {
    seq = _seq;
    countryCode = _countryCode;
    areaNetCode = _areaNetCode;
    dialNum = _dialNum;
    type = _type;
  } // ctor

} // class PartyContactNum
