package HighSpeed;


/**
* HighSpeed/Party.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HighSpeedExt.idl
* Tuesday, December 6, 2016 9:17:28 PM IST
*/

public final class Party implements org.omg.CORBA.portable.IDLEntity
{
  public int seq = (int)0;

  // Details Id
  public int icapId = (int)0;

  // Icap ID
  public String icapRole = null;

  // Icap Role
  public String titleId = null;

  // Subscriber's Title e.g. Mr, Mrs, Prof
  public String surname = null;

  // Subscriber's Surname
  public String firstName = null;

  // Subscriber's First Name
  public String initials = null;

  // Subscriber's Initials
  public String langCode = null;

  // Subscriber's Language
  public String birthDate = null;

  // Subscriber's date of birth
  public String activeYN = null;

  // Subscriber's status flag
  public String listedYN = null;

  // List subscriber on national directory flag
  public String gender = null;

  // Subscriber's Gender
  public HighSpeed.PartyContact contactList[] = null;

  // Customer Contact List
  public HighSpeed.PartyId idList[] = null;

  // Customer ID List
  public HighSpeed.PartyRole roleList[] = null;

  // Role list
  public HighSpeed.PartyContactNum contactNumList[] = null;

  public Party ()
  {
  } // ctor

  public Party (int _seq, int _icapId, String _icapRole, String _titleId, String _surname, String _firstName, String _initials, String _langCode, String _birthDate, String _activeYN, String _listedYN, String _gender, HighSpeed.PartyContact[] _contactList, HighSpeed.PartyId[] _idList, HighSpeed.PartyRole[] _roleList, HighSpeed.PartyContactNum[] _contactNumList)
  {
    seq = _seq;
    icapId = _icapId;
    icapRole = _icapRole;
    titleId = _titleId;
    surname = _surname;
    firstName = _firstName;
    initials = _initials;
    langCode = _langCode;
    birthDate = _birthDate;
    activeYN = _activeYN;
    listedYN = _listedYN;
    gender = _gender;
    contactList = _contactList;
    idList = _idList;
    roleList = _roleList;
    contactNumList = _contactNumList;
  } // ctor

} // class Party
