package HighSpeed;

/**
* HighSpeed/PartyRoleHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HighSpeedExt.idl
* Tuesday, December 6, 2016 9:17:28 PM IST
*/

public final class PartyRoleHolder implements org.omg.CORBA.portable.Streamable
{
  public HighSpeed.PartyRole value = null;

  public PartyRoleHolder ()
  {
  }

  public PartyRoleHolder (HighSpeed.PartyRole initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = HighSpeed.PartyRoleHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    HighSpeed.PartyRoleHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return HighSpeed.PartyRoleHelper.type ();
  }

}
