package HighSpeed;

/**
* HighSpeed/PartyHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HighSpeedExt.idl
* Tuesday, December 6, 2016 9:17:28 PM IST
*/

public final class PartyHolder implements org.omg.CORBA.portable.Streamable
{
  public HighSpeed.Party value = null;

  public PartyHolder ()
  {
  }

  public PartyHolder (HighSpeed.Party initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = HighSpeed.PartyHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    HighSpeed.PartyHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return HighSpeed.PartyHelper.type ();
  }

}
