package HighSpeed;


/**
* HighSpeed/PartyHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HighSpeedExt.idl
* Tuesday, December 6, 2016 9:17:28 PM IST
*/

abstract public class PartyHelper
{
  private static String  _id = "IDL:HighSpeed/Party:1.0";

  public static void insert (org.omg.CORBA.Any a, HighSpeed.Party that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static HighSpeed.Party extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [16];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[0] = new org.omg.CORBA.StructMember (
            "seq",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[1] = new org.omg.CORBA.StructMember (
            "icapId",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (1);
          _members0[2] = new org.omg.CORBA.StructMember (
            "icapRole",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (10);
          _members0[3] = new org.omg.CORBA.StructMember (
            "titleId",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[4] = new org.omg.CORBA.StructMember (
            "surname",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[5] = new org.omg.CORBA.StructMember (
            "firstName",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (40);
          _members0[6] = new org.omg.CORBA.StructMember (
            "initials",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (3);
          _members0[7] = new org.omg.CORBA.StructMember (
            "langCode",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (19);
          _members0[8] = new org.omg.CORBA.StructMember (
            "birthDate",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (1);
          _members0[9] = new org.omg.CORBA.StructMember (
            "activeYN",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (1);
          _members0[10] = new org.omg.CORBA.StructMember (
            "listedYN",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (1);
          _members0[11] = new org.omg.CORBA.StructMember (
            "gender",
            _tcOf_members0,
            null);
          _tcOf_members0 = HighSpeed.PartyContactHelper.type ();
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (HighSpeed.PartyContactListHelper.id (), "PartyContactList", _tcOf_members0);
          _members0[12] = new org.omg.CORBA.StructMember (
            "contactList",
            _tcOf_members0,
            null);
          _tcOf_members0 = HighSpeed.PartyIdHelper.type ();
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (HighSpeed.PartyIdListHelper.id (), "PartyIdList", _tcOf_members0);
          _members0[13] = new org.omg.CORBA.StructMember (
            "idList",
            _tcOf_members0,
            null);
          _tcOf_members0 = HighSpeed.PartyRoleHelper.type ();
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (HighSpeed.PartyRoleListHelper.id (), "PartyRoleList", _tcOf_members0);
          _members0[14] = new org.omg.CORBA.StructMember (
            "roleList",
            _tcOf_members0,
            null);
          _tcOf_members0 = HighSpeed.PartyContactNumHelper.type ();
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (HighSpeed.PartyContactNumListHelper.id (), "PartyContactNumList", _tcOf_members0);
          _members0[15] = new org.omg.CORBA.StructMember (
            "contactNumList",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (HighSpeed.PartyHelper.id (), "Party", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static HighSpeed.Party read (org.omg.CORBA.portable.InputStream istream)
  {
    HighSpeed.Party value = new HighSpeed.Party ();
    value.seq = istream.read_long ();
    value.icapId = istream.read_long ();
    value.icapRole = istream.read_string ();
    if (value.icapRole.length () > (1))
      throw new org.omg.CORBA.MARSHAL (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    value.titleId = istream.read_string ();
    if (value.titleId.length () > (10))
      throw new org.omg.CORBA.MARSHAL (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    value.surname = istream.read_string ();
    value.firstName = istream.read_string ();
    value.initials = istream.read_string ();
    if (value.initials.length () > (40))
      throw new org.omg.CORBA.MARSHAL (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    value.langCode = istream.read_string ();
    if (value.langCode.length () > (3))
      throw new org.omg.CORBA.MARSHAL (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    value.birthDate = istream.read_string ();
    if (value.birthDate.length () > (19))
      throw new org.omg.CORBA.MARSHAL (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    value.activeYN = istream.read_string ();
    if (value.activeYN.length () > (1))
      throw new org.omg.CORBA.MARSHAL (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    value.listedYN = istream.read_string ();
    if (value.listedYN.length () > (1))
      throw new org.omg.CORBA.MARSHAL (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    value.gender = istream.read_string ();
    if (value.gender.length () > (1))
      throw new org.omg.CORBA.MARSHAL (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    value.contactList = HighSpeed.PartyContactListHelper.read (istream);
    value.idList = HighSpeed.PartyIdListHelper.read (istream);
    value.roleList = HighSpeed.PartyRoleListHelper.read (istream);
    value.contactNumList = HighSpeed.PartyContactNumListHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, HighSpeed.Party value)
  {
    ostream.write_long (value.seq);
    ostream.write_long (value.icapId);
    if (value.icapRole.length () > (1))      throw new org.omg.CORBA.MARSHAL (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    ostream.write_string (value.icapRole);
    if (value.titleId.length () > (10))      throw new org.omg.CORBA.MARSHAL (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    ostream.write_string (value.titleId);
    ostream.write_string (value.surname);
    ostream.write_string (value.firstName);
    if (value.initials.length () > (40))      throw new org.omg.CORBA.MARSHAL (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    ostream.write_string (value.initials);
    if (value.langCode.length () > (3))      throw new org.omg.CORBA.MARSHAL (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    ostream.write_string (value.langCode);
    if (value.birthDate.length () > (19))      throw new org.omg.CORBA.MARSHAL (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    ostream.write_string (value.birthDate);
    if (value.activeYN.length () > (1))      throw new org.omg.CORBA.MARSHAL (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    ostream.write_string (value.activeYN);
    if (value.listedYN.length () > (1))      throw new org.omg.CORBA.MARSHAL (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    ostream.write_string (value.listedYN);
    if (value.gender.length () > (1))      throw new org.omg.CORBA.MARSHAL (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    ostream.write_string (value.gender);
    HighSpeed.PartyContactListHelper.write (ostream, value.contactList);
    HighSpeed.PartyIdListHelper.write (ostream, value.idList);
    HighSpeed.PartyRoleListHelper.write (ostream, value.roleList);
    HighSpeed.PartyContactNumListHelper.write (ostream, value.contactNumList);
  }

}
