package HighSpeed;


/**
* HighSpeed/PartyContactNumListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HighSpeedExt.idl
* Tuesday, December 6, 2016 9:17:28 PM IST
*/


// Party Contact Number list
public final class PartyContactNumListHolder implements org.omg.CORBA.portable.Streamable
{
  public HighSpeed.PartyContactNum value[] = null;

  public PartyContactNumListHolder ()
  {
  }

  public PartyContactNumListHolder (HighSpeed.PartyContactNum[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = HighSpeed.PartyContactNumListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    HighSpeed.PartyContactNumListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return HighSpeed.PartyContactNumListHelper.type ();
  }

}
