package HighSpeed;


/**
* HighSpeed/PartyRole.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HighSpeedExt.idl
* Tuesday, December 6, 2016 9:17:28 PM IST
*/

public final class PartyRole implements org.omg.CORBA.portable.IDLEntity
{
  public int seq = (int)0;

  // Unique ID
  public String roleType = null;

  // Agent or Subscriber indicator
  public int suSeq = (int)0;

  public PartyRole ()
  {
  } // ctor

  public PartyRole (int _seq, String _roleType, int _suSeq)
  {
    seq = _seq;
    roleType = _roleType;
    suSeq = _suSeq;
  } // ctor

} // class PartyRole
