package HighSpeed;


/**
* HighSpeed/PartyId.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HighSpeedExt.idl
* Tuesday, December 6, 2016 9:17:28 PM IST
*/

public final class PartyId implements org.omg.CORBA.portable.IDLEntity
{
  public int seq = (int)0;

  // Unique ID
  public String countryId = null;

  // Country of issue of ID document
  public String idNumber = null;

  // Indentification number
  public String idType = null;

  public PartyId ()
  {
  } // ctor

  public PartyId (int _seq, String _countryId, String _idNumber, String _idType)
  {
    seq = _seq;
    countryId = _countryId;
    idNumber = _idNumber;
    idType = _idType;
  } // ctor

} // class PartyId
