package HighSpeed;

/**
* HighSpeed/PartyIdHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HighSpeedExt.idl
* Tuesday, December 6, 2016 9:17:28 PM IST
*/

public final class PartyIdHolder implements org.omg.CORBA.portable.Streamable
{
  public HighSpeed.PartyId value = null;

  public PartyIdHolder ()
  {
  }

  public PartyIdHolder (HighSpeed.PartyId initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = HighSpeed.PartyIdHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    HighSpeed.PartyIdHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return HighSpeed.PartyIdHelper.type ();
  }

}
