package HighSpeed;

/**
* HighSpeed/PartyContactNumHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HighSpeedExt.idl
* Tuesday, December 6, 2016 9:17:28 PM IST
*/

public final class PartyContactNumHolder implements org.omg.CORBA.portable.Streamable
{
  public HighSpeed.PartyContactNum value = null;

  public PartyContactNumHolder ()
  {
  }

  public PartyContactNumHolder (HighSpeed.PartyContactNum initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = HighSpeed.PartyContactNumHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    HighSpeed.PartyContactNumHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return HighSpeed.PartyContactNumHelper.type ();
  }

}
