package HighSpeed;


/**
* HighSpeed/PartyIdListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HighSpeedExt.idl
* Tuesday, December 6, 2016 9:17:28 PM IST
*/


// Party ID list
public final class PartyIdListHolder implements org.omg.CORBA.portable.Streamable
{
  public HighSpeed.PartyId value[] = null;

  public PartyIdListHolder ()
  {
  }

  public PartyIdListHolder (HighSpeed.PartyId[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = HighSpeed.PartyIdListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    HighSpeed.PartyIdListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return HighSpeed.PartyIdListHelper.type ();
  }

}
