package HighSpeed;


/**
* HighSpeed/PartyContactHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HighSpeedExt.idl
* Tuesday, December 6, 2016 9:17:28 PM IST
*/

abstract public class PartyContactHelper
{
  private static String  _id = "IDL:HighSpeed/PartyContact:1.0";

  public static void insert (org.omg.CORBA.Any a, HighSpeed.PartyContact that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static HighSpeed.PartyContact extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [12];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[0] = new org.omg.CORBA.StructMember (
            "seq",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (1);
          _members0[1] = new org.omg.CORBA.StructMember (
            "addressInd",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (19);
          _members0[2] = new org.omg.CORBA.StructMember (
            "fromDate",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[3] = new org.omg.CORBA.StructMember (
            "address1",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[4] = new org.omg.CORBA.StructMember (
            "address2",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[5] = new org.omg.CORBA.StructMember (
            "address3",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[6] = new org.omg.CORBA.StructMember (
            "suburb",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[7] = new org.omg.CORBA.StructMember (
            "town",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (19);
          _members0[8] = new org.omg.CORBA.StructMember (
            "toDate",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (12);
          _members0[9] = new org.omg.CORBA.StructMember (
            "postalCode",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (2);
          _members0[10] = new org.omg.CORBA.StructMember (
            "countryId",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[11] = new org.omg.CORBA.StructMember (
            "region",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (HighSpeed.PartyContactHelper.id (), "PartyContact", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static HighSpeed.PartyContact read (org.omg.CORBA.portable.InputStream istream)
  {
    HighSpeed.PartyContact value = new HighSpeed.PartyContact ();
    value.seq = istream.read_long ();
    value.addressInd = istream.read_string ();
    if (value.addressInd.length () > (1))
      throw new org.omg.CORBA.MARSHAL (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    value.fromDate = istream.read_string ();
    if (value.fromDate.length () > (19))
      throw new org.omg.CORBA.MARSHAL (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    value.address1 = istream.read_string ();
    value.address2 = istream.read_string ();
    value.address3 = istream.read_string ();
    value.suburb = istream.read_string ();
    value.town = istream.read_string ();
    value.toDate = istream.read_string ();
    if (value.toDate.length () > (19))
      throw new org.omg.CORBA.MARSHAL (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    value.postalCode = istream.read_string ();
    if (value.postalCode.length () > (12))
      throw new org.omg.CORBA.MARSHAL (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    value.countryId = istream.read_string ();
    if (value.countryId.length () > (2))
      throw new org.omg.CORBA.MARSHAL (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    value.region = istream.read_string ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, HighSpeed.PartyContact value)
  {
    ostream.write_long (value.seq);
    if (value.addressInd.length () > (1))      throw new org.omg.CORBA.MARSHAL (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    ostream.write_string (value.addressInd);
    if (value.fromDate.length () > (19))      throw new org.omg.CORBA.MARSHAL (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    ostream.write_string (value.fromDate);
    ostream.write_string (value.address1);
    ostream.write_string (value.address2);
    ostream.write_string (value.address3);
    ostream.write_string (value.suburb);
    ostream.write_string (value.town);
    if (value.toDate.length () > (19))      throw new org.omg.CORBA.MARSHAL (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    ostream.write_string (value.toDate);
    if (value.postalCode.length () > (12))      throw new org.omg.CORBA.MARSHAL (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    ostream.write_string (value.postalCode);
    if (value.countryId.length () > (2))      throw new org.omg.CORBA.MARSHAL (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    ostream.write_string (value.countryId);
    ostream.write_string (value.region);
  }

}
