package HighSpeed;


/**
* HighSpeed/PartyContactNumHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HighSpeedExt.idl
* Tuesday, December 6, 2016 9:17:28 PM IST
*/

abstract public class PartyContactNumHelper
{
  private static String  _id = "IDL:HighSpeed/PartyContactNum:1.0";

  public static void insert (org.omg.CORBA.Any a, HighSpeed.PartyContactNum that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static HighSpeed.PartyContactNum extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [5];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[0] = new org.omg.CORBA.StructMember (
            "seq",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (15);
          _members0[1] = new org.omg.CORBA.StructMember (
            "countryCode",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (15);
          _members0[2] = new org.omg.CORBA.StructMember (
            "areaNetCode",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (15);
          _members0[3] = new org.omg.CORBA.StructMember (
            "dialNum",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (1);
          _members0[4] = new org.omg.CORBA.StructMember (
            "type",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (HighSpeed.PartyContactNumHelper.id (), "PartyContactNum", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static HighSpeed.PartyContactNum read (org.omg.CORBA.portable.InputStream istream)
  {
    HighSpeed.PartyContactNum value = new HighSpeed.PartyContactNum ();
    value.seq = istream.read_long ();
    value.countryCode = istream.read_string ();
    if (value.countryCode.length () > (15))
      throw new org.omg.CORBA.MARSHAL (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    value.areaNetCode = istream.read_string ();
    if (value.areaNetCode.length () > (15))
      throw new org.omg.CORBA.MARSHAL (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    value.dialNum = istream.read_string ();
    if (value.dialNum.length () > (15))
      throw new org.omg.CORBA.MARSHAL (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    value.type = istream.read_string ();
    if (value.type.length () > (1))
      throw new org.omg.CORBA.MARSHAL (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, HighSpeed.PartyContactNum value)
  {
    ostream.write_long (value.seq);
    if (value.countryCode.length () > (15))      throw new org.omg.CORBA.MARSHAL (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    ostream.write_string (value.countryCode);
    if (value.areaNetCode.length () > (15))      throw new org.omg.CORBA.MARSHAL (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    ostream.write_string (value.areaNetCode);
    if (value.dialNum.length () > (15))      throw new org.omg.CORBA.MARSHAL (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    ostream.write_string (value.dialNum);
    if (value.type.length () > (1))      throw new org.omg.CORBA.MARSHAL (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    ostream.write_string (value.type);
  }

}
