package HighSpeed;


/**
* HighSpeed/PartyContactListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HighSpeedExt.idl
* Tuesday, December 6, 2016 9:17:28 PM IST
*/


// Party Contact list
public final class PartyContactListHolder implements org.omg.CORBA.portable.Streamable
{
  public HighSpeed.PartyContact value[] = null;

  public PartyContactListHolder ()
  {
  }

  public PartyContactListHolder (HighSpeed.PartyContact[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = HighSpeed.PartyContactListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    HighSpeed.PartyContactListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return HighSpeed.PartyContactListHelper.type ();
  }

}
