package HighSpeed;


/**
* HighSpeed/RequestResultListHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HighSpeedExt.idl
* Tuesday, December 6, 2016 9:17:28 PM IST
*/


// Service request result list
abstract public class RequestResultListHelper
{
  private static String  _id = "IDL:HighSpeed/RequestResultList:1.0";

  public static void insert (org.omg.CORBA.Any a, HighSpeed.RequestResult[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static HighSpeed.RequestResult[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = HighSpeed.RequestResultHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (HighSpeed.RequestResultListHelper.id (), "RequestResultList", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static HighSpeed.RequestResult[] read (org.omg.CORBA.portable.InputStream istream)
  {
    HighSpeed.RequestResult value[] = null;
    int _len0 = istream.read_long ();
    value = new HighSpeed.RequestResult[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = HighSpeed.RequestResultHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, HighSpeed.RequestResult[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      HighSpeed.RequestResultHelper.write (ostream, value[_i0]);
  }

}
