package HighSpeed;


/**
* HighSpeed/RequestResult.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HighSpeedExt.idl
* Tuesday, December 6, 2016 9:17:28 PM IST
*/

public final class RequestResult implements org.omg.CORBA.portable.IDLEntity
{
  public String resultName = null;

  // Result Attribute Name
  public String resultValue = null;

  public RequestResult ()
  {
  } // ctor

  public RequestResult (String _resultName, String _resultValue)
  {
    resultName = _resultName;
    resultValue = _resultValue;
  } // ctor

} // class RequestResult
