package HighSpeed;


/**
* HighSpeed/RequestResultListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HighSpeedExt.idl
* Tuesday, December 6, 2016 9:17:28 PM IST
*/


// Service request result list
public final class RequestResultListHolder implements org.omg.CORBA.portable.Streamable
{
  public HighSpeed.RequestResult value[] = null;

  public RequestResultListHolder ()
  {
  }

  public RequestResultListHolder (HighSpeed.RequestResult[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = HighSpeed.RequestResultListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    HighSpeed.RequestResultListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return HighSpeed.RequestResultListHelper.type ();
  }

}
