package HighSpeed;

/**
* HighSpeed/RequestResultHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HighSpeedExt.idl
* Tuesday, December 6, 2016 9:17:28 PM IST
*/

public final class RequestResultHolder implements org.omg.CORBA.portable.Streamable
{
  public HighSpeed.RequestResult value = null;

  public RequestResultHolder ()
  {
  }

  public RequestResultHolder (HighSpeed.RequestResult initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = HighSpeed.RequestResultHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    HighSpeed.RequestResultHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return HighSpeed.RequestResultHelper.type ();
  }

}
