package HighSpeed;


/**
* HighSpeed/ServiceActionListHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HighSpeedExt.idl
* Tuesday, December 6, 2016 9:17:28 PM IST
*/


// Service action list
abstract public class ServiceActionListHelper
{
  private static String  _id = "IDL:HighSpeed/ServiceActionList:1.0";

  public static void insert (org.omg.CORBA.Any a, HighSpeed.ServiceAction[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static HighSpeed.ServiceAction[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = HighSpeed.ServiceActionHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (HighSpeed.ServiceActionListHelper.id (), "ServiceActionList", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static HighSpeed.ServiceAction[] read (org.omg.CORBA.portable.InputStream istream)
  {
    HighSpeed.ServiceAction value[] = null;
    int _len0 = istream.read_long ();
    value = new HighSpeed.ServiceAction[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = HighSpeed.ServiceActionHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, HighSpeed.ServiceAction[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      HighSpeed.ServiceActionHelper.write (ostream, value[_i0]);
  }

}
