package HighSpeed;

/**
* HighSpeed/ServiceActionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HighSpeedExt.idl
* Tuesday, December 6, 2016 9:17:28 PM IST
*/

public final class ServiceActionHolder implements org.omg.CORBA.portable.Streamable
{
  public HighSpeed.ServiceAction value = null;

  public ServiceActionHolder ()
  {
  }

  public ServiceActionHolder (HighSpeed.ServiceAction initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = HighSpeed.ServiceActionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    HighSpeed.ServiceActionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return HighSpeed.ServiceActionHelper.type ();
  }

}
