package HighSpeed;


/**
* HighSpeed/ServiceActionListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HighSpeedExt.idl
* Tuesday, December 6, 2016 9:17:28 PM IST
*/


// Service action list
public final class ServiceActionListHolder implements org.omg.CORBA.portable.Streamable
{
  public HighSpeed.ServiceAction value[] = null;

  public ServiceActionListHolder ()
  {
  }

  public ServiceActionListHolder (HighSpeed.ServiceAction[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = HighSpeed.ServiceActionListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    HighSpeed.ServiceActionListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return HighSpeed.ServiceActionListHelper.type ();
  }

}
