package HighSpeed;


/**
* HighSpeed/SubAttributeListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HighSpeedExt.idl
* Tuesday, December 6, 2016 9:17:28 PM IST
*/


// Subscriber Attribute List
public final class SubAttributeListHolder implements org.omg.CORBA.portable.Streamable
{
  public HighSpeed.SubAttribute value[] = null;

  public SubAttributeListHolder ()
  {
  }

  public SubAttributeListHolder (HighSpeed.SubAttribute[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = HighSpeed.SubAttributeListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    HighSpeed.SubAttributeListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return HighSpeed.SubAttributeListHelper.type ();
  }

}
