package HighSpeed;

/**
* HighSpeed/SubAttributeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HighSpeedExt.idl
* Tuesday, December 6, 2016 9:17:28 PM IST
*/

public final class SubAttributeHolder implements org.omg.CORBA.portable.Streamable
{
  public HighSpeed.SubAttribute value = null;

  public SubAttributeHolder ()
  {
  }

  public SubAttributeHolder (HighSpeed.SubAttribute initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = HighSpeed.SubAttributeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    HighSpeed.SubAttributeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return HighSpeed.SubAttributeHelper.type ();
  }

}
