package HighSpeed;


/**
* HighSpeed/SubAttribute.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HighSpeedExt.idl
* Tuesday, December 6, 2016 9:17:28 PM IST
*/

public final class SubAttribute implements org.omg.CORBA.portable.IDLEntity
{
  public String dateFrom = null;

  // Start date of the subscriber attribute
  public String dateTo = null;

  // End date of the subscriber
  public String benefitStartDate = null;

  // Date subscriber 's VCRP benefits start
  public String attCatID = null;

  // Attribute category id
  public String attCatDescription = null;

  // Attribute category description
  public String attTypeID = null;

  // Attribute type id
  public String attTypeDescription = null;

  public SubAttribute ()
  {
  } // ctor

  public SubAttribute (String _dateFrom, String _dateTo, String _benefitStartDate, String _attCatID, String _attCatDescription, String _attTypeID, String _attTypeDescription)
  {
    dateFrom = _dateFrom;
    dateTo = _dateTo;
    benefitStartDate = _benefitStartDate;
    attCatID = _attCatID;
    attCatDescription = _attCatDescription;
    attTypeID = _attTypeID;
    attTypeDescription = _attTypeDescription;
  } // ctor

} // class SubAttribute
