package HighSpeed;


/**
* HighSpeed/TaskResult.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HighSpeedExt.idl
* Tuesday, December 6, 2016 9:17:28 PM IST
*/


// Task result
public class TaskResult implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 3;
  private static HighSpeed.TaskResult[] __array = new HighSpeed.TaskResult [__size];

  public static final int _successful = 0;
  public static final HighSpeed.TaskResult successful = new HighSpeed.TaskResult(_successful);
  public static final int _failed = 1;
  public static final HighSpeed.TaskResult failed = new HighSpeed.TaskResult(_failed);
  public static final int _unknown = 2;
  public static final HighSpeed.TaskResult unknown = new HighSpeed.TaskResult(_unknown);

  public int value ()
  {
    return __value;
  }

  public static HighSpeed.TaskResult from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected TaskResult (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class TaskResult
