package HighSpeed;


/**
* HighSpeed/Version.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HighSpeedExt.idl
* Tuesday, December 6, 2016 9:17:28 PM IST
*/

public interface Version
{

  // Module version
  public static final String value = "2.0.1";
}
